import type { Attendance } from '@/types'
import { formatDate } from '@/lib/utils'

export async function exportAttendancePDF(logs: Attendance[], totalPresentToday: number, activeSessions: number) {
  // Lazy load PDF libraries
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])

  const doc = new jsPDF()

  // Header title block
  doc.setFontSize(18)
  doc.setTextColor(5, 150, 105) // Green var(--success-600)
  doc.text('Attendance Logs - GymOS', 14, 20)

  doc.setFontSize(9)
  doc.setTextColor(115, 115, 115) // Grey text
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, 14, 26)
  doc.text(`Today's Footfall: ${totalPresentToday} | Active Sessions: ${activeSessions}`, 14, 31)

  // Map only user-facing values (exclude internal IDs, tenant IDs, system IDs)
  const tableColumn = ['Member Name', 'Member Code', 'Check-In', 'Check-Out', 'Method', 'Notes', 'Date']
  const tableRows = logs.map((l) => {
    const checkInTime = new Date(l.check_in_at).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
    const checkOutTime = l.check_out_at ? new Date(l.check_out_at).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : 'Checked In'
    return [
      l.member_name || '—',
      l.member_code || '—',
      checkInTime,
      checkOutTime,
      l.method.toUpperCase(),
      l.notes || '—',
      formatDate(l.check_in_at)
    ]
  })

  autoTable(doc, {
    startY: 37,
    head: [tableColumn],
    body: tableRows,
    theme: 'striped',
    headStyles: { fillColor: [5, 150, 105] }, // Green
    styles: { fontSize: 8 },
    didDrawPage: (data) => {
      // Professional Footer
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      
      const pageCount = (doc as any).internal.getNumberOfPages()
      const currentPage = data.pageNumber
      const footerText = `Generated by GymOS | Page ${currentPage} of ${pageCount}`
      const generatedAtText = `Generated At: ${new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}`
      
      doc.text(footerText, 14, doc.internal.pageSize.height - 10)
      doc.text(generatedAtText, doc.internal.pageSize.width - doc.getTextWidth(generatedAtText) - 14, doc.internal.pageSize.height - 10)
    }
  })

  doc.save('gymos_attendance_logs.pdf')
}
