import type { Expense, ExpenseCategory } from '@/types'
import { formatDate } from '@/lib/utils'

const categoryLabels: Record<ExpenseCategory, string> = {
  rent: 'Rent & Lease',
  electricity: 'Electricity Bill',
  staff_salary: 'Staff Salary',
  equipment_repair: 'Equipment Repair',
  cleaning: 'Cleaning',
  supplements_purchase: 'Supplements',
  marketing: 'Marketing',
  maintenance: 'Maintenance',
  water: 'Water',
  internet: 'Internet/WiFi',
  other: 'Other Misc',
}

export async function exportExpensesPDF(expenses: Expense[], totalRecorded: number, totalPlanned: number) {
  // Lazy load PDF libraries
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])

  const doc = new jsPDF()

  // Header title block
  doc.setFontSize(18)
  doc.setTextColor(220, 38, 38) // Crimson Red var(--danger-600)
  doc.text('Expenses Ledger - GymOS', 14, 20)

  doc.setFontSize(9)
  doc.setTextColor(115, 115, 115) // Grey text
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, 14, 26)
  doc.text(`Total Outflows Paid: INR ${totalRecorded.toLocaleString('en-IN')}`, 14, 31)
  doc.text(`Planned & Budgeted: INR ${totalPlanned.toLocaleString('en-IN')}`, 14, 36)

  // Map only user-facing values
  const tableColumn = ['Category', 'Amount (INR)', 'Billing Date', 'Cycle', 'Status', 'Description']
  const tableRows = expenses.map((e) => [
    categoryLabels[e.category] || e.category,
    e.amount.toLocaleString('en-IN'),
    formatDate(e.expense_date),
    e.is_recurring ? (e.frequency?.toUpperCase() || 'RECURRING') : 'One-time',
    e.status === 'planned' ? 'Planned' : 'Paid',
    e.description || '—'
  ])

  autoTable(doc, {
    startY: 42,
    head: [tableColumn],
    body: tableRows,
    theme: 'striped',
    headStyles: { fillColor: [220, 38, 38] }, // Crimson Red
    styles: { fontSize: 8 },
    didDrawPage: (data) => {
      // Professional Footer
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      
      const pageCount = (doc as any).internal.getNumberOfPages()
      const currentPage = data.pageNumber
      const footerText = `Generated by GymOS | Page ${currentPage} of ${pageCount}`
      const generatedAtText = `Generated At: ${new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}`
      
      doc.text(footerText, 14, doc.internal.pageSize.height - 10)
      doc.text(generatedAtText, doc.internal.pageSize.width - doc.getTextWidth(generatedAtText) - 14, doc.internal.pageSize.height - 10)
    }
  })

  doc.save('gymos_expenses_ledger.pdf')
}
