import type { Payment } from '@/types'
import { formatDate } from '@/lib/utils'

export async function exportPaymentsPDF(payments: Payment[], totalCollected: number) {
  // Lazy load the PDF libraries on demand
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])

  const doc = new jsPDF()

  // Header title block
  doc.setFontSize(18)
  doc.setTextColor(79, 70, 229) // Indigo var(--primary-600)
  doc.text('Payments Ledger - GymOS', 14, 20)

  doc.setFontSize(9)
  doc.setTextColor(115, 115, 115) // Grey text
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, 14, 26)
  doc.text(`Total Dues Collected: INR ${totalCollected.toLocaleString('en-IN')}`, 14, 31)

  // Map only user-facing values (exclude internal DB ids/tenant fields)
  const tableColumn = ['Receipt No', 'Member Name', 'Member ID', 'Amount (INR)', 'Method', 'Date', 'Description']
  const tableRows = payments.map((p) => [
    p.receipt_number || 'Draft',
    p.member_name || 'Member',
    p.member_id,
    p.amount.toString(),
    p.payment_method.toUpperCase(),
    formatDate(p.paid_at),
    p.description || '—'
  ])

  autoTable(doc, {
    startY: 37,
    head: [tableColumn],
    body: tableRows,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229] }, // Indigo
    styles: { fontSize: 8 },
    didDrawPage: (data) => {
      // Professional Footer metadata block
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      
      const pageCount = (doc as any).internal.getNumberOfPages()
      const currentPage = data.pageNumber
      const footerText = `Generated by GymOS | Page ${currentPage} of ${pageCount}`
      const generatedAtText = `Generated At: ${new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}`
      
      doc.text(footerText, 14, doc.internal.pageSize.height - 10)
      doc.text(generatedAtText, doc.internal.pageSize.width - doc.getTextWidth(generatedAtText) - 14, doc.internal.pageSize.height - 10)
    }
  })

  doc.save('gymos_payments_history.pdf')
}
