export async function exportReportsPDF(
  calculatedMetrics: any[],
  monthlyFinanceData: any[],
  expenseCategoriesBreakdown: any[],
  memberGrowthData: any[],
  dateRangeLabel: string,
  dateRange: string
) {
  // Lazy load PDF libraries
  const [{ jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ])

  const doc = new jsPDF()

  // Header title block
  doc.setFontSize(18)
  doc.setTextColor(79, 70, 229) // Indigo var(--primary-600)
  doc.text('Business Insights & Financial Report', 14, 20)

  doc.setFontSize(10)
  doc.setTextColor(115, 115, 115)
  doc.text(`Report Period: ${dateRangeLabel}`, 14, 26)
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-IN')}`, 14, 31)

  // Page tracking for didDrawPage footer callback
  const reportFooterCallback = (data: any) => {
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    const pageCount = (doc as any).internal.getNumberOfPages()
    const currentPage = data.pageNumber
    const footerText = `Generated by GymOS | Page ${currentPage} of ${pageCount}`
    const generatedAtText = `Generated At: ${new Date().toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}`
    
    doc.text(footerText, 14, doc.internal.pageSize.height - 10)
    doc.text(generatedAtText, doc.internal.pageSize.width - doc.getTextWidth(generatedAtText) - 14, doc.internal.pageSize.height - 10)
  }

  // Section 1: Overview Metrics
  doc.setFontSize(12)
  doc.setTextColor(31, 41, 55)
  doc.text('1. Overview Summary Metrics', 14, 40)

  const overviewCols = ['Metric', 'Current Value', 'Trend/Difference']
  const overviewRows = calculatedMetrics.map((m) => [
    m.label,
    m.value.toString(),
    m.trendValue || '—'
  ])

  autoTable(doc, {
    startY: 44,
    head: [overviewCols],
    body: overviewRows,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229] },
    styles: { fontSize: 8 },
    didDrawPage: reportFooterCallback,
  })

  let nextY = (doc as any).lastAutoTable.finalY + 12

  // Section 2: Cashflow & Monthly Financial Data
  doc.setFontSize(12)
  doc.setTextColor(31, 41, 55)
  doc.text('2. Monthly Financial Data (Last 6 Months)', 14, nextY)

  const financeCols = ['Month', 'Revenue (INR)', 'Expenses (INR)', 'Net Profit (INR)']
  const financeRows = monthlyFinanceData.map((row) => [
    row.month,
    row.revenue.toLocaleString('en-IN'),
    row.expenses.toLocaleString('en-IN'),
    (row.revenue - row.expenses).toLocaleString('en-IN')
  ])

  autoTable(doc, {
    startY: nextY + 4,
    head: [financeCols],
    body: financeRows,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229] },
    styles: { fontSize: 8 },
    didDrawPage: reportFooterCallback,
  })

  nextY = (doc as any).lastAutoTable.finalY + 12

  // Check page height before rendering next sections
  if (nextY > 240) {
    doc.addPage()
    nextY = 20
  }

  // Section 3: Expense Category Breakdown
  doc.setFontSize(12)
  doc.setTextColor(31, 41, 55)
  doc.text('3. Expense Breakdown by Category', 14, nextY)

  const expenseCols = ['Category', 'Amount (INR)', 'Percentage (%)']
  const expenseRows = expenseCategoriesBreakdown.map((cat) => [
    cat.name,
    cat.amount.toLocaleString('en-IN'),
    `${cat.percentage}%`
  ])

  autoTable(doc, {
    startY: nextY + 4,
    head: [expenseCols],
    body: expenseRows,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229] },
    styles: { fontSize: 8 },
    didDrawPage: reportFooterCallback,
  })

  nextY = (doc as any).lastAutoTable.finalY + 12

  if (nextY > 240) {
    doc.addPage()
    nextY = 20
  }

  // Section 4: Member Status Growth
  doc.setFontSize(12)
  doc.setTextColor(31, 41, 55)
  doc.text('4. Member Growth Data', 14, nextY)

  const memberCols = ['Month', 'Active Members', 'Frozen Members', 'Expired Members']
  const memberRows = memberGrowthData.map((m) => [
    m.month,
    m.active.toString(),
    m.frozen.toString(),
    m.expired.toString()
  ])

  autoTable(doc, {
    startY: nextY + 4,
    head: [memberCols],
    body: memberRows,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229] },
    styles: { fontSize: 8 },
    didDrawPage: reportFooterCallback,
  })

  doc.save(`gymos_business_report_${dateRange}.pdf`)
}
