import type { Expense } from '@/types'

export const initialExpenses: Expense[] = [
  {
    id: 'exp_001',
    tenant_id: 'tenant_001',
    branch_id: null,
    category: 'rent',
    amount: 25000,
    description: 'Monthly gym premise rent',
    receipt_url: null,
    expense_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_recurring: true,
    recorded_by: 'usr_001',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'exp_002',
    tenant_id: 'tenant_001',
    branch_id: null,
    category: 'electricity',
    amount: 8500,
    description: 'Electricity bill for May 2026',
    receipt_url: null,
    expense_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_recurring: false,
    recorded_by: 'usr_001',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'exp_003',
    tenant_id: 'tenant_001',
    branch_id: null,
    category: 'staff_salary',
    amount: 15000,
    description: 'Part-time trainer salary',
    receipt_url: null,
    expense_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_recurring: true,
    recorded_by: 'usr_001',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'exp_004',
    tenant_id: 'tenant_001',
    branch_id: null,
    category: 'equipment_repair',
    amount: 3200,
    description: 'Treadmill belt replacement',
    receipt_url: null,
    expense_date: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    is_recurring: false,
    recorded_by: 'usr_001',
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
]
