import type { Lead, LeadFollowup, TrialMember } from '@/types'

export const initialLeads: Lead[] = [
  {
    id: 'lead_001',
    tenant_id: 'tenant_001',
    first_name: 'Arjun',
    last_name: 'Mehta',
    phone: '+919876501234',
    email: 'arjun.mehta@gmail.com',
    gender: 'male',
    age_range: '25-30',
    source: 'instagram',
    referral_member_id: null,
    interest: 'Weight training, CrossFit',
    status: 'new',
    lost_reason: null,
    notes: 'Saw Instagram reel, interested in 3-month plan',
    next_followup_at: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'usr_001',
    converted_member_id: null,
    converted_at: null,
    created_by: 'usr_001',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'lead_002',
    tenant_id: 'tenant_001',
    first_name: 'Kavya',
    last_name: 'Nair',
    phone: '+919812345678',
    email: 'kavya.nair@yahoo.com',
    gender: 'female',
    age_range: '20-25',
    source: 'walk_in',
    referral_member_id: null,
    interest: 'Yoga, Cardio',
    status: 'contacted',
    lost_reason: null,
    notes: 'Walked in yesterday, wants to start from next Monday',
    next_followup_at: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'usr_001',
    converted_member_id: null,
    converted_at: null,
    created_by: 'usr_001',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'lead_003',
    tenant_id: 'tenant_001',
    first_name: 'Rohit',
    last_name: 'Verma',
    phone: '+919998887776',
    email: null,
    gender: 'male',
    age_range: '30-35',
    source: 'referral',
    referral_member_id: 'mem_001',
    interest: 'General fitness',
    status: 'follow_up',
    lost_reason: null,
    notes: 'Referred by Rahul Sharma. Wants personal training.',
    next_followup_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'usr_001',
    converted_member_id: null,
    converted_at: null,
    created_by: 'usr_001',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'lead_004',
    tenant_id: 'tenant_001',
    first_name: 'Deepika',
    last_name: 'Sharma',
    phone: '+919123456789',
    email: 'deepika.s@gmail.com',
    gender: 'female',
    age_range: '25-30',
    source: 'google',
    referral_member_id: null,
    interest: 'Weight loss, Zumba',
    status: 'trial',
    lost_reason: null,
    notes: 'Found us on Google Maps. Currently on 3-day trial.',
    next_followup_at: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'usr_001',
    converted_member_id: null,
    converted_at: null,
    created_by: 'usr_001',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'lead_005',
    tenant_id: 'tenant_001',
    first_name: 'Vikram',
    last_name: 'Joshi',
    phone: '+919876543210',
    email: 'vikram.j@outlook.com',
    gender: 'male',
    age_range: '35-40',
    source: 'whatsapp',
    referral_member_id: null,
    interest: 'Strength training',
    status: 'converted',
    lost_reason: null,
    notes: 'Converted to 6-month plan',
    next_followup_at: null,
    assigned_to: 'usr_001',
    converted_member_id: 'mem_010',
    converted_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'usr_001',
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'lead_006',
    tenant_id: 'tenant_001',
    first_name: 'Neha',
    last_name: 'Gupta',
    phone: '+919765432100',
    email: null,
    gender: 'female',
    age_range: '20-25',
    source: 'facebook',
    referral_member_id: null,
    interest: 'General fitness',
    status: 'lost',
    lost_reason: 'Too expensive',
    notes: 'Asked for rates, said too expensive. Suggested starter plan.',
    next_followup_at: null,
    assigned_to: 'usr_001',
    converted_member_id: null,
    converted_at: null,
    created_by: 'usr_001',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'lead_007',
    tenant_id: 'tenant_001',
    first_name: 'Siddharth',
    last_name: 'Patel',
    phone: '+919654321000',
    email: 'sid.patel@gmail.com',
    gender: 'male',
    age_range: '20-25',
    source: 'instagram',
    referral_member_id: null,
    interest: 'Bodybuilding',
    status: 'new',
    lost_reason: null,
    notes: 'DMed on Instagram asking about membership',
    next_followup_at: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'usr_001',
    converted_member_id: null,
    converted_at: null,
    created_by: 'usr_001',
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
  {
    id: 'lead_008',
    tenant_id: 'tenant_001',
    first_name: 'Ananya',
    last_name: 'Reddy',
    phone: '+919543210000',
    email: 'ananya.r@gmail.com',
    gender: 'female',
    age_range: '25-30',
    source: 'referral',
    referral_member_id: 'mem_002',
    interest: 'Pilates, Yoga',
    status: 'contacted',
    lost_reason: null,
    notes: 'Referred by Priya Patel. Wants morning batch.',
    next_followup_at: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    assigned_to: 'usr_001',
    converted_member_id: null,
    converted_at: null,
    created_by: 'usr_001',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    deleted_at: null,
  },
]

export const initialFollowups: LeadFollowup[] = [
  {
    id: 'fu_001',
    lead_id: 'lead_003',
    contacted_by: 'usr_001',
    contact_method: 'call',
    outcome: 'interested',
    notes: 'Spoke for 10 minutes. Very interested. Wants to visit tomorrow.',
    next_followup_at: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    contacted_by_name: 'Rajesh Kumar',
  },
  {
    id: 'fu_002',
    lead_id: 'lead_003',
    contacted_by: 'usr_001',
    contact_method: 'whatsapp',
    outcome: 'thinking',
    notes: 'Sent pricing details on WhatsApp. Said he will think about it.',
    next_followup_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    contacted_by_name: 'Rajesh Kumar',
  },
  {
    id: 'fu_003',
    lead_id: 'lead_002',
    contacted_by: 'usr_001',
    contact_method: 'call',
    outcome: 'interested',
    notes: 'Called her. She wants to start Monday. Will visit Saturday for registration.',
    next_followup_at: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    contacted_by_name: 'Rajesh Kumar',
  },
]

export const initialTrialMembers: TrialMember[] = [
  {
    id: 'trial_001',
    lead_id: 'lead_004',
    start_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    trial_days: 3,
    status: 'active',
    attendance_count: 1,
    feedback: null,
  },
]
