import type { Staff } from '@/types'

const TENANT = 'tenant_001'
const now = new Date()

function daysAgo(days: number): string {
  return new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString()
}

export const initialStaff: Staff[] = [
  {
    id: 'staff_001',
    tenant_id: TENANT,
    first_name: 'Vikram',
    last_name: 'Singh',
    phone: '+919876543210',
    email: 'vikram.singh@gym.com',
    role: 'trainer',
    status: 'active',
    joined_at: daysAgo(365),
    salary_amount: 25000,
    salary_frequency: 'monthly',
    shift: 'morning',
    photo_url: null,
    emergency_contact: '+919876500001',
    notes: 'Certified personal trainer. Specializes in strength training.',
    created_at: daysAgo(365),
    updated_at: daysAgo(10),
    deleted_at: null,
  },
  {
    id: 'staff_002',
    tenant_id: TENANT,
    first_name: 'Pooja',
    last_name: 'Mehta',
    phone: '+919876543211',
    email: 'pooja.mehta@gym.com',
    role: 'trainer',
    status: 'active',
    joined_at: daysAgo(240),
    salary_amount: 22000,
    salary_frequency: 'monthly',
    shift: 'evening',
    photo_url: null,
    emergency_contact: '+919876500002',
    notes: 'Yoga and CrossFit instructor.',
    created_at: daysAgo(240),
    updated_at: daysAgo(5),
    deleted_at: null,
  },
  {
    id: 'staff_003',
    tenant_id: TENANT,
    first_name: 'Ankit',
    last_name: 'Verma',
    phone: '+919876543212',
    email: 'ankit.v@gym.com',
    role: 'receptionist',
    status: 'active',
    joined_at: daysAgo(180),
    salary_amount: 15000,
    salary_frequency: 'monthly',
    shift: 'full_day',
    photo_url: null,
    emergency_contact: '+919876500003',
    notes: 'Handles front desk and member check-ins.',
    created_at: daysAgo(180),
    updated_at: daysAgo(2),
    deleted_at: null,
  },
  {
    id: 'staff_004',
    tenant_id: TENANT,
    first_name: 'Ramesh',
    last_name: 'Yadav',
    phone: '+919876543213',
    email: null,
    role: 'cleaning',
    status: 'active',
    joined_at: daysAgo(300),
    salary_amount: 10000,
    salary_frequency: 'monthly',
    shift: 'morning',
    photo_url: null,
    emergency_contact: '+919876500004',
    notes: null,
    created_at: daysAgo(300),
    updated_at: daysAgo(30),
    deleted_at: null,
  },
  {
    id: 'staff_005',
    tenant_id: TENANT,
    first_name: 'Deepak',
    last_name: 'Sharma',
    phone: '+919876543214',
    email: 'deepak@gym.com',
    role: 'manager',
    status: 'active',
    joined_at: daysAgo(400),
    salary_amount: 35000,
    salary_frequency: 'monthly',
    shift: 'full_day',
    photo_url: null,
    emergency_contact: '+919876500005',
    notes: 'Operations manager. Manages scheduling and staff coordination.',
    created_at: daysAgo(400),
    updated_at: daysAgo(1),
    deleted_at: null,
  },
  {
    id: 'staff_006',
    tenant_id: TENANT,
    first_name: 'Neha',
    last_name: 'Gupta',
    phone: '+919876543215',
    email: 'neha.gupta@gym.com',
    role: 'trainer',
    status: 'on_leave',
    joined_at: daysAgo(150),
    salary_amount: 20000,
    salary_frequency: 'monthly',
    shift: 'flexible',
    photo_url: null,
    emergency_contact: '+919876500006',
    notes: 'On medical leave. Expected return: next month.',
    created_at: daysAgo(150),
    updated_at: daysAgo(7),
    deleted_at: null,
  },
]
